project:
  type: website
  output-dir: docs

website:
  comments:
    giscus:
      repo: kbodwin/paRticles
  title: "paRticles"
  navbar:
    right:
      - icon: butterfly
        href: https://bsky.app/profile/kellybodwin.com
      - icon: mastodon
        href: https://fosstodon.org/@kellybodwin
      - icon: linkedin
        href: https://linkedin.com/in/kelly-bodwin-9009061a/
      - icon: github
        href: https://github.com/kbodwin/paRticles

format:
  html:
    theme: [pulse, custom.scss]
    css: styles.css

